Update gea2-logger.py
File "/home/pi/ge-appliances-re/geabus-demos/gea2-logger.py", line 54
    print "Received message: Dst: " + dst + " Src: " + src + " Cmd: " + cmd + " numErds: " + erdCount + " Payload: " + payload
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Received message: Dst: " + dst + " Src: " + src + " Cmd: " + cmd + " numErds: " + erdCount + " Payload: " + payload)?